import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ReduxProvider from "@/store/reduxProvider";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme/theme';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
      <ReduxProvider>
        {children}
      </ReduxProvider>
      </ ThemeProvider>
      </ AppRouterCacheProvider>
      </body>
    </html>
  );
}
